sensors:
  - hand_camera_pointcloud

hand_camera_pointcloud:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /hand_camera/points
  max_range: 2.0
  point_subsample: 1
  padding_offset: 0.1
  padding_scale: 1.0
  max_update_rate: 1.0
  filtered_cloud_topic: /hand_camera/filtered_points