source "https://rubygems.org"
gem "jekyll"
gem "webrick", "~> 1.9"
#gem "github-pages", group: :jekyll_plugins
group :jekyll_plugins do
  gem "jekyll-avatar"
  gem "jekyll-default-layout"
  gem "jekyll-feed"
  gem "jekyll-gist"
  gem "jekyll-optional-front-matter"
  gem "jekyll-paginate"
  gem "jekyll-readme-index"
  gem "jekyll-redirect-from"
  gem "jekyll-relative-links"
  gem "jekyll-remote-theme"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-titles-from-headings"
  gem "addressable", ">= 2.8.0"
end
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
